### ISSUE TITLE
Underwater rain

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#10]
Rain is raining under water.

![screenshot_20200429_114323](https://user-images.githubusercontent.com/25328789/80582306-be978e00-8a0e-11ea-847a-443c624bd8d6.png)

**Comment by oilboi** [comment]
Unfortunately I can't fix this until particles can collide with liquids :L

**Comment by Cassumbra** [comment]
Not sure if it would be possible, and it would be a bandaid fix, but could you make the rain disappear when it reaches y=64 or whatever the water level is using a timer? Additionally, you could possibly check to make sure its an ocean biome before making it disappear if that's something that can be done.

**Comment by oilboi** [comment]
Time for a bandaid
