### ISSUE TITLE
Crafting guide overlaps crafting & smeltig Recipes

### ISSUE THREAD

**Issue by Derneugamer** [oilboi/Crafter#101]
First : Click on a crafting recipe (for example a chestplate)
![screenshot_20200625_190756](https://user-images.githubusercontent.com/66687440/85768488-5ff24600-b719-11ea-83e7-7461e8df1b5b.png)
Then choose an item with a cooking recipe (for example toast)
![screenshot_20200625_190809](https://user-images.githubusercontent.com/66687440/85768661-8d3ef400-b719-11ea-8045-686a98cadb2a.png)
See how both recepies overlap?
PS Idk if recipe is spelled right :/

**Comment by oilboi** [comment]
Ohhh that's what this bug is! Thanks
