### ISSUE TITLE
Improve rain

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#12]
In my opinion, rain is not looking "vertical" enough. The fact that they fall downwards doesn't give me a rainy feeling:
![screenshot_20200508_152103](https://user-images.githubusercontent.com/25328789/81409616-b1ca1700-913f-11ea-831a-5d98fa33cdc4.png)

A quick experiment with longer textures and with`minsize = 0.5`, `maxsize = 4` in the particle definition:
![screenshot_20200508_150751](https://user-images.githubusercontent.com/25328789/81409655-c7d7d780-913f-11ea-8955-24f833ff655f.png)

Would probably look better with gradint alpha mask.

**Comment by oilboi** [comment]
This is implemented, thank you

**Comment by tacotexmex** [comment]
👍 
Together with https://github.com/minetest/minetest/issues/7284 we'll have an amazing athmosphere.
