### ISSUE TITLE
Leaves to drop non-climbable version

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#13]
Because leaves are climbable, player can dig a few trees stand without reason to build ladders. Because of this I suggest that "on-tree" leaves remain climbable but the dropped version aren't.

**Comment by oilboi** [comment]
Fixed it

**Comment by tacotexmex** [comment]
Leaves doesn't seem to drop at all now?

**Comment by oilboi** [comment]
It's fixed even more now :jack_o_lantern:
