### ISSUE TITLE
Growth node timer catch up

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#15]
One (out of few) benefits of ABM based growth progress is the catch-up feature which enables a just loaded map block to get its wheat growth progress in order for when the player comes back. This improves the ”the world moves with or without me” feeling, which is important for immersion.

Node timers doesn’t seem to have that feature. Can it be recreated somehow?

This applies to other nodes as well, such as the furnace.

**Comment by oilboi** [comment]
Furnaces are going to be a bit difficult to rewrite, I will have to keep this open until that is finished. The saplings do use ABMs again with catch up

**Comment by tacotexmex** [comment]
Or perhaps one ABM for all growth wouldn't be that bad? 🙃 🤔

**Comment by oilboi** [comment]
Yes, it's fully implemented, now all growth uses abms with catchup so you can walk away and then come back to a fully grown garden

**Comment by tacotexmex** [comment]
Rad. I should be worth it, performance-wise. Also, the larger the wheat fields the more worth having an ABM.

**Comment by oilboi** [comment]
Today I will swap the furnace to ABM and make it work a bit better

**Comment by oilboi** [comment]
This is implemented
