### ISSUE TITLE
CSM WAILA

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#17]
A minimalist non-intrusive WAILA feature could be a good addition. It needs to poll client-side. I wrote a server side version, [pointlib](https://github.com/tacotexmex/pointlib), but that would of course be a lagfest on anything but tiny servers.

**Comment by oilboi** [comment]
https://github.com/oilboi/crafter_client/commit/1e5524aba0033a57b4c337ff7aa89dfbc4fb95fa

Using the bare minimum for now but it's looking good so far

**Comment by tacotexmex** [comment]
Nice! Would be interesting to be able to register events server-side to a callback function in this mod, so that thing's can be interacted with by simply pointing at them. Nodes, but entities too (Endermen, right?).

**Comment by oilboi** [comment]
Oh yes, that is actually extremely possible, I will have to think about this for a few days and make notes as the pathfinding for mobs has to come first

**Comment by oilboi** [comment]
Please open up a new feature request for this

**Comment by tacotexmex** [comment]
#24
