### ISSUE TITLE
Button on piston crashes game

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#2]
![screenshot_20200329_151118](https://user-images.githubusercontent.com/25328789/77849985-d8f00900-71cf-11ea-8a8b-92a98f363f9e.png)

Pressing this button, or digging it, crashes the game.

**Comment by oilboi** [comment]
Fixed it! Now it does nothing. Basically the button turns whatever node it's on into a redstone torch and doing that to the piston crashes it. Hopefully we can get more bug testers to find issues like this!
Thank you for the report.
