### ISSUE TITLE
Smelting ores should provide XP if following MC

### ISSUE THREAD

**Issue by leorockway** [oilboi/Crafter#21]
In Minecraft, smelting ores into ingots provides XP.

**Comment by Cassumbra** [comment]
might not be as important since you get xp from iron already from just mining it

**Comment by oilboi** [comment]
He is right, because the ores that drop themselves can be mined over and over again for infinite XP, unfortunately. I'll have to overhaul the furnace today

**Comment by tacotexmex** [comment]
Isn’t that avoidable if ore drop ingots or lumps instead?

**Comment by oilboi** [comment]
It'll confuse people coming from MC to drop lumps tbh

**Comment by tacotexmex** [comment]
I thought that stone with ore dropped ingots in MC?

**Comment by oilboi** [comment]
Gold and iron drop the source node

**Comment by tacotexmex** [comment]
I see. How about correcting this inconsistency now that there’s a chance? 😃

**Comment by oilboi** [comment]
This is fixed
