### ISSUE TITLE
Spider's eyes should glow red at night

### ISSUE THREAD

**Issue by leorockway** [oilboi/Crafter#28]
Spider's eyes should glow red at night; this makes it easier to spot them. Later once the cave spiders get added, I believe their eyes glow green.

**Comment by tacotexmex** [comment]
I suppose the eyes need to be their own pair of entities for that partial glow to work. 🤔

**Comment by oilboi** [comment]
Entity glowing is currently broken in the engine, so I have implemented the code, but the eyes do not glow yet

**Comment by oilboi** [comment]
This has been implemented
