### ISSUE TITLE
Lava / fires should keep burning the player

### ISSUE THREAD

**Issue by leorockway** [oilboi/Crafter#31]
Even after getting out of lava or other fires, the player should stay burning for a bit and keep getting damage for a randomized amount of seconds (unless the player jumps in water).

Also, I don't know if MC does this, but I think it would make sense for wooden items in the inventory to have a chance to burn too (ie, get destroyed and losing them).

**Comment by oilboi** [comment]
Oooo, let's see if I can make this happen
