### ISSUE TITLE
Size of stacks

### ISSUE THREAD

**Issue by leorockway** [oilboi/Crafter#32]
I feel that the stack size being pretty much unlimited makes survival much less challenging and it also renders chests somewhat irrelevant.

I suggest that in order to be able to carry such big stacks one shoud first craft an enchanted item (akin to a DnD bag of holding).

**Comment by oilboi** [comment]
The scale of MT and Crafter makes backpacks a requirement still once you get past diamond tools

**Comment by oilboi** [comment]
I'm closing this because you still need backpacks even with the extreme amount of items you can carry
