### ISSUE TITLE
Snowman behavior

### ISSUE THREAD

**Issue by tacotexmex** [oilboi/Crafter#33]
Doesn't it makes sense for the snowman mob to become more powerful and/or grow in size when throwing snowballs at it?

Also, it would make sense if it dropped some snowballs _and_ two sticks. 😁

**Comment by leorockway** [comment]
I mentioned this to oilboi in IRC: snowmen should also drop carrots once that crop becomes part of the game.

**Comment by tacotexmex** [comment]
443ddf136885109f52d53220104e6321f3c51932
