### ISSUE TITLE
Networking

### ISSUE THREAD

**Issue by bzoss** [oilboi/Crafter#56]
@oilboi I've worked recently with Wuzzy on MCL2 - if you haven't seen it, you should take a look. Each of you are doing a fantastic job building various Minecraft nuances into the Minetest experience.

As we hash out features for MCL2, your Crafter mods came up on a few occasions. I have to say, between you and Wuzzy, there is a near complete rendition of Minecraft ready to go. For example, breeding works in MCL2, yet I see it's an issue you're currently working.

At any rate, I think you should take a look at the MCL2 project and join forces - it would result in the best possible outcome.

Your optimizations, pathfinding, and player mechanics are spot on, BTW.

All the best.

**Comment by bzoss** [comment]
Pulling for review - MCL2 is missing out on the great advances you've made.

**Comment by oilboi** [comment]
I joined the irc :P

**Comment by bzoss** [comment]
IRC?  If that translates to the MCL2 team - great!

**Comment by leorockway** [comment]
Things that Crafter has that MCL2 doesn't:

* FOV running
* Double tap running
* Mobs' head tracking
* Player's head tracking
* Swimming animation
* XP
* Death animations
* Player's burning status
* Jetpack (Elytra replacement?)
* Sneaking animation
* Glow in the dark eyes for spiders

Things that MCL2 has that Crafter doesn't:
* Biomes
* Most MC structures
* Mobs' heads
* Mob spawners
* Records / record players
* Breeding
* Nametags
* Additional mobs
* Anvils
* The end
* Lava / water drips
* Paintings
* Banners
* Armor stands
* Several blocks like terracota, concrete, bookshelves
* All types of trees and wood blocks
* Mushrooms
* Coral
* Flowers
*  Cauldrons
* Ender chests
* Shulker boxes
* Ender perls / eyes of ender
* Trapdoors
* Item frame
* Lilly pads

Probably forgetting things on both sides, but combining these things would create better games on both sides, even though the objectives of each project are different.

**Comment by bzoss** [comment]
Great breakdown of each project. Just discussing head tracking doesn't do the Crafter project justice - mob animations are phenomenal and on-point.  Head tracking is great, but more complex components such as path finding really add an element of sophistication that bumps the gameplay experience up a few notches.

**Comment by bzoss** [comment]
::Showing Persistence:: 
Lets get these two projects linked up!

**Comment by oilboi** [comment]
I looked through the code of Mineclone 2 and I can guarantee that the code in there is so complicated I could never implement my ideas into it :L

**Comment by bzoss** [comment]
The biggest challenge to coding with MCL2 will be appending mcl_ to the front of most standard functions. Based on what you have already accomplished, you can handle the challenge.  
I personally think you should start with player/mob animations.

**Comment by bzoss** [comment]
If I can't get you onboard, I'm going to leverage some of your work to port it over into MCL2.  The player and mob mechanics are just too good.

**Comment by oilboi** [comment]
Go right ahead my man :D I've got a bit too much on my hands to work on another project right now

**Comment by bzoss** [comment]
I can appreciate your workload - the preferred outcome of this recruiting venture is that you end up contributing to a similar cause, which is already a bit further along.  The result (in a not-so-distant future) would be a truly Minecraft-like experience.

We'll still be there if you change your mind.
