### ISSUE TITLE
Hyper Jump / "Dolphin Jump"

### ISSUE THREAD

**Issue by Derneugamer** [oilboi/Crafter#67]
If you are swimming in a 1 high water and the you go out whilst being near a steep slope you can make a hyperjump

**Comment by Derneugamer** [comment]
![screenshot_20200619_233132](https://user-images.githubusercontent.com/66687440/85180969-16bb7580-b285-11ea-833d-41a414c86c01.png)
The slope where it happened to me

**Comment by Derneugamer** [comment]
It happened to me agin apperently you need to press shift too

**Comment by Derneugamer** [comment]
Ok it happends even if you jump in water whilst sprinting (same place as upstairs)

**Comment by oilboi** [comment]
This is fixed :)
