### ISSUE TITLE
Bizzare Waterbucket in nether 

### ISSUE THREAD

**Issue by Derneugamer** [oilboi/Crafter#72]
If you place a water bucket in the Nether it explodes, If you die threw the explosion you will respawn with an empty bucket in your inv 
Sometimes it happends too that you when you die threw the explosion and you get a water and an empty bucket.
(If you get catapulted in lava threw the explosion sometimes you will start to burn after respawn (like you were in lava) 
_{I hope its clear what I mean}_

**Comment by oilboi** [comment]
Hahaha, consider that a gift from the Nether

**Comment by oilboi** [comment]
I'm going to test this
