### ISSUE TITLE
Snowlayers can fall infinitly?

### ISSUE THREAD

**Issue by Derneugamer** [oilboi/Crafter#79]
I found this :
![screenshot_20200623_191413](https://user-images.githubusercontent.com/66687440/85434164-ed049600-b585-11ea-9fa6-00490bb60510.png)
The snowlayer wont stop falling until I update the block under it

**Comment by oilboi** [comment]
This is actually a builtin falling entity problem, I'll look at seeing how to fix it. I'll have to create a new version of the falling entity
