### ISSUE TITLE
Game screws up my settings

### ISSUE THREAD

**Issue by Wuzzy2** [oilboi/Crafter#8]
The game violently overwrites a couple of very technical and important settings to insane values.
Like, `dedicated_server_step` is set to the insanely low value 0.00001.

The problem is, this overwrites things in my global `minetest.conf`, so it affects other settings. You use `minetest.settings.set()` to set default settings, but this is dangerous as it screws up my config.

The recommended way to set default settings in Minetest is by adding a `minetest.conf` in the game folder and writing in the default settings you like, just like in the global `minetest.conf`.

**Comment by Wuzzy2** [comment]
Also: It is questionable if you need to set all those settings in the first place (especially `dedicated_server_step`).

Quote celeron55 about `dedicated_server_step`:

> values in the range of about 0.01 to 0.2 might make sense

(but tbh, I don't think you need to set this setting at all. Feel free to drop by in IRC one day :) )

**Comment by oilboi** [comment]
Fixed! https://github.com/oilboi/Crafter/commit/b53a93354a6efffb01fa9b23b5f1c945eddabc1e
