### ISSUE TITLE
Falling sand/gravel stairs are bizzare

### ISSUE THREAD

**Issue by Derneugamer** [oilboi/Crafter#91]
The orientation chenges when the stairs is an entity ,but the its get back to the normal again

**Comment by Derneugamer** [comment]
Falling Walls and fences are bizzare to when they fall on a wall or fence

**Comment by oilboi** [comment]
This isn't actually a bug :L

**Comment by Derneugamer** [comment]
It's odd I didn't knew (sorry) :(

**Comment by oilboi** [comment]
I can fix the rotation though!
